name: cash
recipe: symfony
proxy:
  mailhog:
    - mail.cash.lndo.site
config:
  webroot: public
  php: '7.4'
  via: apache:2.4
  database: mysql:5.7
  xdebug: true
  config:
    server: config/server.conf
services:
  myservice:
    type: mysql
    portforward: 53600
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
    portforward: 1028